//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazzCPO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public string Date { get; set; }
        public int Quantity { get; set; }
        public decimal Total { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
